FROM debian:trixie-slim
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates libssl3t64 && rm -rf /var/lib/apt/lists/*
COPY target/geopop-api-arm64 /usr/local/bin/geopop-api
EXPOSE 8080
CMD ["geopop-api"]
